name: Deploy to EC2

on:
  push:
    branches:
      - dev  # 監聽 dev 分支變動

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          JWTSECRET: ${{ secrets.JWTSECRET }}
          DBSTR: ${{ secrets.DBSTR }} # 之後移除
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << EOF
            cd /home/ec2-user/Parking-Assistant-Backend
            git checkout dev
            git pull
            
            mkdir -p nginx_secrets/accounts
            sudo chown -R ec2-user:ec2-user nginx_secrets
            sudo chmod -R 755 nginx_secrets
            
            echo "POSTGRES_USER=${POSTGRES_USER}" > .env
            echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
            echo "JWTSECRET=${JWTSECRET}" >>.env
            echo "DBSTR=${DBSTR}" >>.env
            
            docker-compose up --build -d
            docker system prune -f
          EOF