name: Deploy to EC2

on:
  push:
    branches:
      - dev  # 監聽 dev 分支變動

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
            cd /home/ec2-user/Parking-Assistant-Backend
            git checkout dev
            git pull
            
            # 創建 .env 文件
            cat << 'ENVEOF' > .env
            POSTGRES_USER=$POSTGRES_USER
            POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            PGADMIN_EMAIL=$PGADMIN_EMAIL
            ENVEOF
            
            # 修復權限問題
            sudo chown -R ec2-user:ec2-user .
            sudo chmod -R 755 .
            
            docker-compose up --build -d
            docker system prune -f
EOF
